language: cpp

dist: focal

compiler:
- g++

os:
- linux

branches: master

addons:
  apt:
    packages:
      - gcc
      - g++
      - cmake
      - libhwloc-dev
      - openmpi-bin
      - libopenmpi-dev

before_script:
  - mkdir build_openmp
  - cd build_openmp
  - cmake -DEULER2D_KOKKOS_BUILD=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_HWLOC=ON ..

script:
  - make
