name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # apparently checkout@v2 is not capable of initializing git submodules ?
    - name: checkout repository
      uses: actions/checkout@v2
      with: 
        submodules: true
    - name: configure
      run: mkdir build_openmp && cd build_openmp && cmake -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_HWLOC=ON ..
    - name: make
      run: make
    - name: make check
      run: make check
